apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sports-store-247/sports-store-deployments
    targetRevision: main
    path: helm/sports-store
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudcart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
